name: GameFunXiao
version: '${project.version}'
main: org.gamefunxiao.GameFunXiao
bootstrapper: org.gamefunxiao.GameFunBootstrap
api-version: '1.21'
authors: [ bzd ]
description: GameFun 小游戏插件 - 猎人游戏
dependencies:
  server:
    Vault:
      load: BEFORE
      required: false
    PlaceholderAPI:
      load: BEFORE
      required: false
    Multiverse-Core:
      load: BEFORE
      required: false
