name: BrickGuard
version: 1.0.0
main: org.yuyun.brickguard.YuYunBrickGuardPlugin
api-version: '1.21.11'
authors: [qiyuan]
description: 板砖守卫战
commands:
  brickguard:
    description: 板砖守卫战主命令
    usage: /brickguard <menu|rooms|rank|quick|create|leave|map>
    aliases: [bg, bgsw, yzsw]
permissions:
  brickguard.use:
    default: true
  brickguard.admin:
    default: op
  yuyunbrickguard.use:
    default: true
  yuyunbrickguard.admin:
    default: op
